# Generated by Django 3.2 on 2022-06-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_auto_20220611_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='club.Group'),
        ),
    ]
